#!/usr/bin/env bash
# Bootstrap a fresh macOS machine into this dotfiles setup.
# Usage: git clone <url> [<dir>] && cd <dir> && ./install.sh
# The repo can live anywhere; install.sh points chezmoi at ./home/ and applies.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 1. Homebrew
if ! command -v brew >/dev/null 2>&1; then
  echo "==> Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# 2. Runtime dependencies
echo "==> Installing runtime dependencies (brew bundle)"
brew bundle --file="$SCRIPT_DIR/Brewfile"

# 3. Oh My Zsh
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  echo "==> Installing Oh My Zsh"
  git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"
fi

# 4. tmux TPM + plugins
if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
  echo "==> Installing tmux TPM"
  git clone --depth=1 https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi
"$HOME/.tmux/plugins/tpm/bin/install_plugins" || true

# 5. Point chezmoi at this repo's home/ source dir, then apply.
# The config is live-generated (not tracked) because the clone location
# varies per machine. Re-running install.sh is safe (idempotent).
echo "==> Configuring chezmoi (sourceDir=$SCRIPT_DIR/home)"
mkdir -p "$HOME/.config/chezmoi"
cat > "$HOME/.config/chezmoi/chezmoi.toml" <<EOF
# Generated by install.sh — not tracked (clone location varies per machine).
# Managed files live in <repo>/home/ (sourceDir below).
sourceDir = "$SCRIPT_DIR/home"

[data]
  name = "George Suarez"
  email = "georgesuarezdev@gmail.com"
EOF
echo "==> Applying dotfiles via chezmoi"
chezmoi apply

chezmoi doctor || true

echo "Done. Open a new shell to load your config."
