"$schema" = 'https://starship.rs/config-schema.json'

palette = 'tokyo-night'
command_timeout = 200

format = """
[░▒▓](lavender)\
$os\
[](bg:blue fg:lavender)\
$directory\
[](fg:blue bg:bg2)\
$git_branch\
$git_status\
[](fg:bg2 bg:bg1)\
$nodejs\
$bun\
$rust\
$python\
[](fg:bg1 bg:bg0)\
$cmd_duration\
[ ](fg:bg0)\
\n$character"""

[palettes.tokyo-night]
lavender = "#a3aed2"
blue = "#769ff0"
bg2 = "#394260"
bg1 = "#212736"
bg0 = "#1d2230"
fg = "#e3e5e5"
muted = "#a0a9cb"
dark = "#090c0c"
green = "#9ece6a"
red = "#f7768e"

[character]
success_symbol = "[❯](bold fg:green)"
error_symbol = "[✗](bold fg:red)"

[directory]
style = "fg:fg bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:bg2"
format = '[[ $symbol $branch ](fg:blue bg:bg2)]($style)'

[git_status]
style = "bg:bg2"
format = '[[($all_status$ahead_behind )](fg:blue bg:bg2)]($style)'

[nodejs]
symbol = ""
style = "bg:bg1"
format = '[[ $symbol ($version) ](fg:blue bg:bg1)]($style)'

[bun]
symbol = ""
style = "bg:bg1"
format = '[[ $symbol ($version) ](fg:blue bg:bg1)]($style)'

[rust]
symbol = ""
style = "bg:bg1"
format = '[[ $symbol ($version) ](fg:blue bg:bg1)]($style)'

[python]
symbol = ""
style = "bg:bg1"
format = '[[ $symbol ($version )($virtualenv )](fg:blue bg:bg1)]($style)'

[golang]
disabled = true
symbol = ""
style = "bg:bg1"
format = '[[ $symbol ($version) ](fg:blue bg:bg1)]($style)'

[php]
disabled = true
symbol = ""
style = "bg:bg1"
format = '[[ $symbol ($version) ](fg:blue bg:bg1)]($style)'

[cmd_duration]
min_time = 500
style = "bg:bg0"
format = '[[  $duration ](fg:muted bg:bg0)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:bg0"
format = '[[  $time ](fg:muted bg:bg0)]($style)'

[os]
style = "bg:lavender fg:dark"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
